### ISSUE TITLE
add macOS installer

### ISSUE THREAD

**Issue by GiienaAstrella** [Ghifari160/migrate#5]
While it's not too involved to install command line apps by hand on macOS, it would be nice to have a `.pkg` installer. A [Homebrew](https://brew.sh) Formulae would also be nice, though it probably has to be done outside of the official Taps.

Tasks:
- [x] Refactor Actions workflows
- [x] Add macOS installer
- [x] Add Homebrew Formulae

**Comment by Ghifari160** [comment]
Task:

- [ ] Refactor Actions workflows
- [ ] Add macOS installer
- [ ] Add Homebrew Formulae

**Comment by GiienaAstrella** [comment]
`v0.1.0` and `v0.2.0` has been added to a [Homebrew Tap](https://github.com/Ghifari160/homebrew-tools). Future releases will be added to the Tap as well. And eventually, we'll add an Actions workflow to automatically update the Formula in the Tap.
